root: true
extends:
  - "eslint:recommended"
  - "@unocss"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "@nuxt/eslint-config"
  - "plugin:prettier/recommended"
plugins:
  - "only-warn"
ignorePatterns:
  - "dist/"
settings:
  import/resolver:
    typescript: true
    node: true
env:
  node: true
  browser: true
rules:
  no-var: "warn"
  prefer-const: "warn"
  prettier/prettier: "warn"
  import/newline-after-import: "warn"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - caughtErrors: "none"
  quotes:
    - "warn"
    - "double"
    - avoidEscape: true
      allowTemplateLiterals: false
  sort-imports:
    - "warn"
    - ignoreDeclarationSort: true
  import/order:
    - "warn"
    - groups: [builtin, external, internal, parent, sibling, index]
      pathGroups:
        - pattern: "@/**"
          group: "internal"
        - pattern: "~/**"
          group: "internal"
      alphabetize:
        order: "asc"
  vue/multi-word-component-names: "off"
