name: "CI"

on: [push, pull_request]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v2

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: ${{ !env.ACT && 'pnpm' || '' }}

      - name: "Install dependencies"
        run: pnpm install

      - name: "Check format"
        run: pnpm run format:check
