name: "Deploy"

on:
  push:
    paths-ignore:
      - "README.md"
      - "README.site.md"
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Extract engines"
        id: engines
        run: echo ::set-output name=node::$(jq --raw-output .engines.node ./package.json)

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v2

      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.engines.outputs.node }}
          cache: ${{ !env.ACT && 'pnpm' || '' }}

      - name: "Install dependencies"
        run: pnpm install --shamefully-hoist

      - name: "Run Generate"
        run: pnpm run generate

      - name: "Upload assets"
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "jcwillox"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
